structure_validation_task:
  description: >
    解析输入的POSCAR文件，提取晶格参数、原子种类及其坐标，进行对称性分析，识别可能的结构缺陷或不稳定因素，并生成一份详细的结构分析报告。
    POSCAR内容：
    ```
    {poscar}
    ```
  expected_output: >
    一份结构分析报告，内容包括：
    - 晶格参数（a, b, c, α, β, γ）
    - 原子类型及其在晶胞中的位置
    - 对称性分析结果
    - 其他任何对结构优化有益的结构文件分析

  agent: structure_validator
