structure_validation_task:
  description: >
    对得到的POSCAR文件内容执行全面结构验证，包含：
    - 使用pymatgen解析并验证基础格式合规性
    - 自动检测坐标越界、原子重叠等致命错误
    - 评估表面/分子体系真空层充分性
    - 验证原子类型与数量声明一致性
    - 检查选择性动力学标记有效性
  expected_output: >
    结构化验证报告包含：
    1. 验证状态标记（通过/警告/失败）
    2. 错误明细表（含行号、错误代码、严重等级）
    3. 自动修正建议（可执行修正方案）
    4. 修正后POSCAR内容（若需要修正）
    格式为：
    POSCAR:
    ```
    POSCAR内容
    ```

  agent: structure_validator

configuration_task:
  description: >
    基于验证后的POSCAR文件生成结构优化参数：
    1. 分析体系维度（块体/表面/分子）
    2. 确定电子自洽收敛标准（EDIFF）
    3. 配置离子弛豫参数（IBRION/NSW）
    4. 生成自适应k点网格（Gamma中心/Monkhorst-Pack）
    5. 设置应力计算标志（ISIF）
  expected_output: >
    包含以下文件的配置文本：
    - INCAR（含参数注释）
    - KPOINTS（含生成逻辑说明注释）

    输出格式为：
    KPOINTS:
    ```
    KPOINTS内容
    ```
    INCAR:
    ```
    INCAR内容
    ```

  agent: vasp_configurator

