vaspkit_task:
  description: >
    POSCAR文件已经在指定存储位置,内容为:
    ```
    {poscar}
    ```
    用户的额外强调信息为"{description}"(可能为空),根据POSCAR的内容和用户的强调信息分析材料并使用合适的参数调用vaspkit工具，工具会自动生成用于结构优化的INCAR和KPOINTS文件。
  expected_output: >
    执行工具调用，返回分析过程及理由
  agent: vaspkit_operator


